version: "3"
services:
  auto-post-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-post-classifier:latest
    ports:
      - "80:80"
    volumes:
      - "./logs:/app/logs"
      - "./responses:/app/responses"
      - "./mock:/app/mock"
      - ".env:/app/.env"
      - "./entrypoint.sh:/app/entrypoint.sh"
