version: "3"
services:
  auto-post-classifer-script:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-post-classifer:latest
    volumes:
      - "./logs:/app/logs"
      - "./output:/app/output"
      - "./data:/app/data"

  auto-post-classifer-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: auto-post-classifer:latest
    ports:
      - "80:80"
    volumes:
      - "./logs:/app/logs"
